l_english:
 
 dif_settings_dif_moderate_title:0 "Settings // Difficulty Scaling §GModerate§!"
 dif_settings_dif_moderate_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 
 dif_settings_dif_hard_title:0 "Settings // Difficulty Scaling §YHard§!"
 dif_settings_on_dif_hard_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 
 dif_settings_dif_nightmare_title:0 "Settings // Difficulty Scaling §ONightmare§!"
 dif_settings_dif_nightmare_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 
 dif_settings_dif_off_title:0 "Settings // Difficulty Scaling is §ROFF§!"
 dif_settings_dif_off_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 

 loanRepaidLocKey:0 "§G[This.loanRepaid.GetValue]§!"
 warsWonLocKey:0 "§G[This.warsWon.GetValue]§!"
 warsLostLocKey:0 "§R[This.warsLost.GetValue]§!"
 battlesWonLocKey:0 "§G[This.battlesWon.GetValue]§!"
 battlesLostLocKey:0 "§R[This.battlesLost.GetValue]§!"
 bankruptcyNumLocKey:0 "§R[This.bankruptcyNum.GetValue]§!"
  
 dif_settings.1.t:0 "Dificulty&AI Settings"
 dif_settings.1.d:0 "The AI is fundamentally bad at certain areas of the game. To compensate for that mod introduces several AI scripts.\n\n§GExpansion Planner§! - Generates Claims for AI, creating more logical routs for AI Expansion. AI will seek to Unify culture, controle Trade nodes, finish conquering states and more. It will not generate claims on allies or friendly countries.\n\n§GAutodev for AI§! - Same auto dev functionality but for AI.\n\n§GAI Building§! - Ensures that AI will continuously build buildings throughout the game. Bypassing pdx building AI weaknesses and bugs.\n\n§GNative Setting§! - Allows you to remove a selected group of natives from the game. Incases where you would want more performance or just dont like having natives in the game.\n\nTotal Army Size in the Game: §G[REB.difTotalArmySize.GetValue]§!\nTotal development in the Game: §G[REB.devTotalvar.GetValue]§!\nTotal development gained: §G[REB.devsumClicks.GetValue]§!\nFrom Auto Dev: §G[REB.autoDev.GetValue]§!"
 opt.dif_settings.enable:0 "§GEnable Scaling Difficulty§!"
 opt.dif_settings.disable:0 "§RDisable Scaling Difficulty§!"
 opt.dif_settings.lock:0 "§RLock Settings§!"
 opt.dif_settings.exit:0 "Close"
 opt.dif_settings.back:0 "Back"
 opt.dif_settings.confirm:0 "§RConfirm§!"
 dif_settings.4.t:0 "Make the changes permanent"
 dif_settings.4.d:0 ""


 opt.dif_settings.Scaling:0 "Scaling Difficulty ([This.ScalingDifficultyLoc])"
 opt.dif_settings.expansion:0 "AI Expansion Planer ([This.ExpansionPlaner])"
 opt.dif_settings.enable.expansion:0 "§GEnabled by Default§!"
 opt.dif_settings.disable.expansion:0 "§RDisable§!"


 opt.dif_settings.build:0 "AI Building ([This.BuildEventLoc])"
 opt.dif_settings.enable.build:0 "§GEnabled by Default§!"
 opt.dif_settings.disable.build:0 "§RDisable§!"
 
 dif_settings.3.t:0 "Feature Setting: AI Auto Development"
 dif_settings.3.d:0 "The AI is really bad at developing their provinces. They will often sit at the monarch point cap for no reason instead of developing. This feature will allow the AI to develop their lowest cost province when the AI hits a predefined threshold of monarch points (scaled to institution penalties)"
 opt.dif_settings.devclick:0 "Auto Dev for AI ([This.DevClickLoc])"
 opt.dif_settings.enable.dev:0 "§GEnabled by Default§! (Recommended)"
 opt.dif_settings.disable.dev:0 "§RDisable§!"
 
 scadifModerateDisabled:0 "§YModerate§!"
 scadifModerateEnabled:0 "§GModerate§!"
 scadifHardDisabled:0 "§YHard§!"
 scadifHardEnabled:0 "§GHard§!"
 scadifNightmareDisabled:0 "§YNightmare§!"
 scadifNightmareEnabled:0 "§GNightmare§!"
 expDisabled:0 "§RDisabled§!"
 expEnabled:0 "§GEnabled§!"
 devclDisabled:0 "§RDisabled§!"
 devclEnabled:0 "§GEnabled§!"
 bevDisabled:0 "§RDisabled§!"
 bevEnabled:0 "§GEnabled§!"

 scadifDisabled:0 "§RDisabled§!"
 scadifModerate:0 "§GModerate§!"
 scadifHard:0 "§YHard§!"
 scadifNightmare:0 "§ONightmare§!"

 opt.native_settings:0 "Native Settings (§YLocked after 1450§!)"
 dif_settings.5.t:0 "Native Settings"
 dif_settings.5.d:0 "Option that allows you to remove Natives from the game. Generally having less countries improves performance.\n\nTags randomly removed at a rate of approximately 1-5 Tags a day.\nKeeping it active for North American Natives for approximately 10-14 days will remove half of the Natives there.\n"

 opt.remove_north_american.confirm:0 "North American Natives ([This.RemovingNorthAmericanNativesLoc])"
 opt.remove_south_american.confirm:0 "South American Natives ([This.RemovingSouthAmericanNativesLoc])"
 opt.remove_aboriginal.confirm:0 "Aboriginal Natives ([This.RemovingAboriginalNativesLoc])"
 opt.remove_polynesian.confirm:0 "Polynesian Natives ([This.RemovingPolynesianNativesLoc])"
 opt.natives.done:0 "Done"
 
 removingNorthEnabled:0 "§RRemoved§!"
 removingNorthDisabled:0 "§GKept§!"
 removingSouthEnabled:0 "§RRemoved§!"
 removingSouthDisabled:0 "§GKept§!"
 removingAboriginalEnabled:0 "§RRemoved§!"
 removingAboriginalDisabled:0 "§GKept§!"
 removingPolynesianEnabled:0 "§RRemoved§!"
 removingPolynesianDisabled:0 "§GKept§!"

 scaling_difficulty_AoDis:0 "Scaling Difficulty"
 scaling_difficulty_AoRef:0 "Scaling Difficulty"
 scaling_difficulty_AoAbs:0 "Scaling Difficulty"
 scaling_difficulty_AoRev:0 "Scaling Difficulty"

 dif_settings.8.t:0 "Scaling Difficulty"
 dif_settings.8.d:0 "Scaling AI bonuses that will increase with every subsequent Age. Limited to AI's that have at least 10 provinces. Primarily gives Monarch point related bonuses. Does Not contain any direct combat bonuses.\n\n§GModerate§! - Small initial AI bonuses. No initial Force Limit bonuses.\n\n§GHard§! - Notable initial AI bonuses. Small initial Force Limit bonuses.\n\n§GNightmare§! - Significant initial AI bonuses. Notable initial Force Limit bonuses."
 opt.scaling_difficulty.moderate:0 "Difficulty: [This.ScalingDifficultyModerate]"
 opt.scaling_difficulty.hard:0 "Difficulty: [This.ScalingDifficultyHard]"
 opt.scaling_difficulty.nightmare:0 "Difficulty: [This.ScalingDifficultyNightmare]"
 