l_english:
 
 dif_settings_on_title:0 "Settings // Difficulty Scaling is §GON§!"
 dif_settings_on_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 
 dif_settings_off_title:0 "Settings // Difficulty Scaling is §ROFF§!"
 dif_settings_off_desc:0 "£dip£ Wars Won: [This.warsWonLoc]\n£dip£ Wars Lost: [This.warsLostLoc]\n£mil£ Battles Won: [This.battlesWonLoc]\n£mil£ Battles Lost: [This.battlesLostLoc]\n¤ Loans Repaid: [This.loanRepaidLoc]\n¤ Bankruptcy: [This.bankruptcyNumLoc]" 

 loanRepaidLocKey:0 "§G[This.loanRepaid.GetValue]§!"
 warsWonLocKey:0 "§G[This.warsWon.GetValue]§!"
 warsLostLocKey:0 "§R[This.warsLost.GetValue]§!"
 battlesWonLocKey:0 "§G[This.battlesWon.GetValue]§!"
 battlesLostLocKey:0 "§R[This.battlesLost.GetValue]§!"
 bankruptcyNumLocKey:0 "§R[This.bankruptcyNum.GetValue]§!"
  
 dif_settings.1.t:0 "Dificulty&AI Settings"
 dif_settings.1.d:0 "The AI is fundamentally bad at certain areas of the game. To compensate for that mod introduces several AI scripts.\n\nScaling Difficulty option allows you to enable additional AI bonuses that will increase with every subsequent Age.\nDoesn't give AI combat bonuses.\nLimited to AI's with at least 10 provinces to avoid excessive deving.\n\nTotal development in the Game §G[REB.devTotalvar.GetValue]§!\nTotal development gained §G[REB.devsumClicks.GetValue]§!\nFrom Auto Dev §G[REB.autoDev.GetValue]§!"
 opt.dif_settings.enable:0 "§GEnable Scaling Difficulty§!"
 opt.dif_settings.disable:0 "§RDisable Scaling Difficulty§!"
 opt.dif_settings.lock:0 "§RLock Settings§!"
 opt.dif_settings.exit:0 "Close"
 opt.dif_settings.back:0 "Back"
 opt.dif_settings.confirm:0 "§RConfirm§!"
 dif_settings.4.t:0 "Make the changes permanent"
 dif_settings.4.d:0 ""


 opt.dif_settings.Scaling:0 "Scaling Difficulty ([This.ScalingDifficultyLoc])"
 opt.dif_settings.expansion:0 "AI Expansion Planer ([This.ExpansionPlaner])"
 opt.dif_settings.enable.expansion:0 "§GEnabled by Default§!"
 opt.dif_settings.disable.expansion:0 "§RDisable§!"


 opt.dif_settings.build:0 "AI Building ([This.BuildEventLoc])"
 opt.dif_settings.enable.build:0 "§GEnabled by Default§!"
 opt.dif_settings.disable.build:0 "§RDisable§!"
 
 dif_settings.3.t:0 "Feature Setting: AI Auto Development"
 dif_settings.3.d:0 "The AI is really bad at developing their provinces. They will often sit at the monarch point cap for no reason instead of developing. This feature will allow the AI to develop their lowest cost province when the AI hits a predefined threshold of monarch points (scaled to institution penalties)"
 opt.dif_settings.devclick:0 "AI Deving ([This.DevClickLoc])"
 opt.dif_settings.enable.dev:0 "§GEnabled by Default§! (Recommended)"
 opt.dif_settings.disable.dev:0 "§RDisable§!"
 
 scadifDisabled:0 "§RDisabled§!"
 scadifEnabled:0 "§GEnabled§!"
 expDisabled:0 "§RDisabled§!"
 expEnabled:0 "§GEnabled§!"
 devclDisabled:0 "§RDisabled§!"
 devclEnabled:0 "§GEnabled§!"
 bevDisabled:0 "§RDisabled§!"
 bevEnabled:0 "§GEnabled§!"

 opt.native_settings:0 "Native Settings (Loked after 1450)"
 dif_settings.5.t:0 "Native Settings"
 dif_settings.5.d:0 "Option that allows you to remove Natives from the game. Generally having less countries improves performance.\n\nTags randomly removed at a rate of approximately 1-5 Tags a day.\nKeeping it active for North American Natives for approximately 10-14 days will remove half of the Natives there.\n"

 opt.remove_north_american.confirm:0 "North American Natives ([This.RemovingNorthAmericanNativesLoc])"
 opt.remove_south_american.confirm:0 "South American Natives ([This.RemovingSouthAmericanNativesLoc])"
 opt.remove_aboriginal.confirm:0 "Aboriginal Natives ([This.RemovingAboriginalNativesLoc])"
 opt.remove_polynesian.confirm:0 "Polynesian Natives ([This.RemovingPolynesianNativesLoc])"
 opt.natives.done:0 "Done"
 
 removingNorthEnabled:0 "§RRemoved§!"
 removingNorthDisabled:0 "§GKept§!"
 removingSouthEnabled:0 "§RRemoved§!"
 removingSouthDisabled:0 "§GKept§!"
 removingAboriginalEnabled:0 "§RRemoved§!"
 removingAboriginalDisabled:0 "§GKept§!"
 removingPolynesianEnabled:0 "§RRemoved§!"
 removingPolynesianDisabled:0 "§GKept§!"

 scaling_difficulty_AoDis:0 "Scaling Difficulty"
 scaling_difficulty_AoRef:0 "Scaling Difficulty"
 scaling_difficulty_AoAbs:0 "Scaling Difficulty"
 scaling_difficulty_AoRev:0 "Scaling Difficulty"


 